site_name: Analysis Facility Docs
theme:
  name: material
  features:
    - instant
nav:
  - Home: "index.md"
  - "Job submission": "job_submission.md"
  - "Coffea Casa":
      - "Basics": "coffeacasa.md"
      - "ServiceX": "servicex.md"
  - "ML platform": "ml_platform.md"
  - XCache: "xcache.md"
